'use strict';

const { contextBridge, ipcRenderer, webUtils } = require('electron');

function subscribe(channel, callback) {
  const listener = (_event, data) => callback(data);
  ipcRenderer.on(channel, listener);
  return () => ipcRenderer.removeListener(channel, listener);
}

contextBridge.exposeInMainWorld('dshDesktop', {
  nativeSettingsView: true,
  sharedConversations: true,
  settingsEmbedded: process.argv.includes('--workbench-settings'),
  showNativeSettings: (payload) => ipcRenderer.invoke('dsh:show-native-settings', payload),
  nativeSettingsReady: () => ipcRenderer.invoke('dsh:native-settings-ready'),
  onNativeSettingsReady: (callback) => subscribe('dsh:native-settings-ready', callback),
  saveCredentials: (payload) => ipcRenderer.invoke('dsh:save-credentials', payload),
  finishOnboarding: () => ipcRenderer.invoke('dsh:finish-onboarding'),
  getState: () => ipcRenderer.invoke('dsh:get-state'),
  openLogs: () => ipcRenderer.invoke('dsh:open-logs'),
  openSettingsWindow: (target) => ipcRenderer.invoke('dsh:open-settings-window', target),
  openMobileAccess: () => ipcRenderer.invoke('dsh:open-mobile-access'),
  remoteControl: (action, payload) => ipcRenderer.invoke('dsh:remote-control', { action, payload }),
  engineSettingsGet: (payload) => ipcRenderer.invoke('dsh:engine-settings-get', payload),
  engineSettingsSave: (payload) => ipcRenderer.invoke('dsh:engine-settings-save', payload),
  runtimeState: () => ipcRenderer.invoke('dsh:runtime-state'),
  runtimeEnsure: (payload) => ipcRenderer.invoke('dsh:runtime-ensure', payload),
  runtimeCheckUpdates: () => ipcRenderer.invoke('dsh:runtime-check-updates'),
  runtimeUpdate: (payload) => ipcRenderer.invoke('dsh:runtime-update', payload),
  downloadSettings: () => ipcRenderer.invoke('dsh:download-settings'),
  downloadSaveSettings: (payload) => ipcRenderer.invoke('dsh:download-save-settings', payload),
  onRuntimeState: (callback) => subscribe('dsh:runtime-state', callback),
  benchmarkState: () => ipcRenderer.invoke('dsh:benchmark-state'),
  benchmarkStart: payload => ipcRenderer.invoke('dsh:benchmark-start', payload),
  benchmarkCancel: () => ipcRenderer.invoke('dsh:benchmark-cancel'),
  benchmarkReport: id => ipcRenderer.invoke('dsh:benchmark-report', { id }),
  benchmarkInstall: engine => ipcRenderer.invoke('dsh:benchmark-install', { engine }),
  benchmarkPrepareLibrary: library => ipcRenderer.invoke('dsh:benchmark-prepare-library', { library }),
  benchmarkExport: id => ipcRenderer.invoke('dsh:benchmark-export', { id }),
  benchmarkDelete: id => ipcRenderer.invoke('dsh:benchmark-delete', { id }),
  apiRouterExport: () => ipcRenderer.invoke('dsh:api-router-export'),
  apiRouterImport: () => ipcRenderer.invoke('dsh:api-router-import'),
  onBenchmarkState: callback => subscribe('dsh:benchmark-state', callback),
  onSettingsNavigate: (callback) => subscribe('dsh:settings-navigate', callback),
  onEngineSettingsChanged: (callback) => subscribe('dsh:engine-settings-changed', callback),
  // Settings
  getSettings: () => ipcRenderer.invoke('dsh:get-settings'),
  saveSettings: (payload) => ipcRenderer.invoke('dsh:save-settings', payload),
  pickFile: (payload) => ipcRenderer.invoke('dsh:pick-file', payload),
  testRuntime: (payload) => ipcRenderer.invoke('dsh:test-runtime', payload),
  applySettings: () => ipcRenderer.invoke('dsh:apply-settings'),
  // Shared API pool (only masked credentials leave the main process).
  openApiSettingsWindow: () => ipcRenderer.invoke('dsh:open-api-settings-window'),
  apiRouterGetState: () => ipcRenderer.invoke('dsh:api-router-get-state'),
  apiRouterSaveConfig: (payload) => ipcRenderer.invoke('dsh:api-router-save-config', payload),
  apiRouterRotate: (model) => ipcRenderer.invoke('dsh:api-router-rotate', model),
  apiRouterReset: (payload) => ipcRenderer.invoke('dsh:api-router-reset', payload),
  onApiRouterState: (callback) => subscribe('dsh:api-router-state', callback),
  ollamaProxyGetState: () => ipcRenderer.invoke('dsh:ollama-proxy-get-state'),
  providerInsights: () => ipcRenderer.invoke('dsh:provider-insights'),
  providerRefresh: (payload) => ipcRenderer.invoke('dsh:provider-refresh', payload),
  providerModels: (payload) => ipcRenderer.invoke('dsh:provider-models', payload),
  providerVerify: (payload) => ipcRenderer.invoke('dsh:provider-verify', payload),
  contextCapacity: () => ipcRenderer.invoke('dsh:context-capacity'),
  contextCapacityStart: payload => ipcRenderer.invoke('dsh:context-capacity-start', payload),
  contextCapacityCancel: () => ipcRenderer.invoke('dsh:context-capacity-cancel'),
  onContextCapacity: callback => subscribe('dsh:context-capacity', callback),
  onProviderInsights: (callback) => subscribe('dsh:provider-insights', callback),
  workbenchSettings: () => ipcRenderer.invoke('dsh:workbench-settings'),
  onLanguageChanged: (callback) => subscribe('dsh:language-changed', callback),
  workbenchSaveSettings: (payload) => ipcRenderer.invoke('dsh:workbench-save-settings', payload),
  archivedSessionsList: () => ipcRenderer.invoke('dsh:archived-sessions-list'),
  archivedSessionAction: (payload) => ipcRenderer.invoke('dsh:archived-session-action', payload),
  storageScan: () => ipcRenderer.invoke('dsh:storage-scan'),
  storageClean: (token) => ipcRenderer.invoke('dsh:storage-clean', { token }),
  onArchivedChanged: (callback) => subscribe('dsh:archived-changed', callback),
  codexDesktopSessions: () => ipcRenderer.invoke('dsh:codex-desktop-sessions'),
  codexDesktopImport: (ids) => ipcRenderer.invoke('dsh:codex-desktop-import', { ids }),
  codexDesktopSync: (id) => ipcRenderer.invoke('dsh:codex-desktop-sync', { id }),
  // Claude Code GUI
  claudeSend: (payload) => ipcRenderer.invoke('dsh:claude-send', payload),
  claudeCancel: (runId) => ipcRenderer.invoke('dsh:claude-cancel', runId),
  claudeGetSettings: () => ipcRenderer.invoke('dsh:claude-get-settings'),
  claudeSaveSettings: (payload) => ipcRenderer.invoke('dsh:claude-save-settings', payload),
  claudeControlRespond: (payload) => ipcRenderer.invoke('dsh:claude-control-respond', payload),
  claudeListSessions: (options) => ipcRenderer.invoke('dsh:claude-list-sessions', options),
  claudeLoadSession: (id) => ipcRenderer.invoke('dsh:claude-load-session', id),
  claudeRenameSession: (payload) => ipcRenderer.invoke('dsh:claude-rename-session', payload),
  claudeArchiveSession: (payload) => ipcRenderer.invoke('dsh:claude-archive-session', payload),
  claudeGoalGet: () => ipcRenderer.invoke('dsh:claude-goal-get'),
  claudeGoalStart: (payload) => ipcRenderer.invoke('dsh:claude-goal-start', payload),
  claudeGoalPause: () => ipcRenderer.invoke('dsh:claude-goal-pause'),
  claudeGoalResume: () => ipcRenderer.invoke('dsh:claude-goal-resume'),
  claudeGoalComplete: () => ipcRenderer.invoke('dsh:claude-goal-complete'),
  claudeGoalClear: () => ipcRenderer.invoke('dsh:claude-goal-clear'),
  claudeMetaOp: (payload) => ipcRenderer.invoke('dsh:claude-meta-op', payload),
  switchMode: (mode) => ipcRenderer.invoke('dsh:switch-mode', mode),
  onHarnessNavigate: callback => subscribe('dsh:harness-navigate', callback),
  conversationCommand: payload => ipcRenderer.invoke('dsh:conversation-command', payload),
  conversationSwitch: payload => ipcRenderer.invoke('dsh:conversation-switch', payload),
  conversationOpenHandoff: payload => ipcRenderer.invoke('dsh:conversation-open-handoff', payload),
  onConversationEvent: callback => subscribe('dsh:conversation-event', callback),
  onConversationGoal: callback => subscribe('dsh:conversation-goal', callback),
  onConversationStatus: callback => subscribe('dsh:conversation-status', callback),
  // Attachments: pick via native dialog / resolve dropped File objects
  pickAttachments: () => ipcRenderer.invoke('dsh:pick-attachments'),
  attachmentPath: (file) => webUtils.getPathForFile(file),
  saveClipboardImage: (payload) => ipcRenderer.invoke('dsh:save-clipboard-image', payload),
  savePastedText: (payload) => ipcRenderer.invoke('dsh:save-pasted-text', payload),
  previewFile: (filePath) => ipcRenderer.invoke('dsh:preview-file', filePath),
  resolveArtifacts: (payload) => ipcRenderer.invoke('dsh:resolve-artifacts', payload),
  openFileExternally: (filePath) => ipcRenderer.invoke('dsh:open-file-externally', filePath),
  onClaudeEvent: (callback) => subscribe('dsh:claude-event', callback),
  onClaudeGoal: (callback) => subscribe('dsh:claude-goal', callback),
  // Shared ACP conversation API; no arbitrary IPC forwarding.
  ...Object.fromEntries(['codex', 'kimi', 'antigravity'].flatMap(engine => ['Send', 'Cancel', 'GetLive', 'GetSettings', 'SaveSettings', 'ControlRespond',
    'ListSessions', 'LoadSession', 'RenameSession', 'ArchiveSession', 'MetaOp',
    'GoalGet', 'GoalStart', 'GoalPause', 'GoalResume', 'GoalComplete', 'GoalClear'].map(action => [
    engine + action, payload => ipcRenderer.invoke('dsh:' + engine + '-' + action.replace(/[A-Z]/g, (c, i) => (i ? '-' : '') + c.toLowerCase()), payload),
  ]))),
  onCodexEvent: callback => subscribe('dsh:codex-event', callback),
  onCodexGoal: callback => subscribe('dsh:codex-goal', callback),
  onCodexAccount: callback => subscribe('dsh:codex-account', callback),
  codexAccountState: () => ipcRenderer.invoke('dsh:codex-account-state'),
  codexAccountRefresh: () => ipcRenderer.invoke('dsh:codex-account-refresh'),
  codexSignIn: () => ipcRenderer.invoke('dsh:codex-sign-in'),
  kimiAccountState: () => ipcRenderer.invoke('dsh:kimi-account-state'),
  kimiAccountRefresh: () => ipcRenderer.invoke('dsh:kimi-account-refresh'),
  kimiSignIn: () => ipcRenderer.invoke('dsh:kimi-sign-in'),
  kimiCancelLogin: () => ipcRenderer.invoke('dsh:kimi-cancel-login'),
  kimiOpenLogin: () => ipcRenderer.invoke('dsh:kimi-open-login'),
  kimiSignOut: () => ipcRenderer.invoke('dsh:kimi-sign-out'),
  onKimiAccount: callback => subscribe('dsh:kimi-account', callback),
  codexSignOut: () => ipcRenderer.invoke('dsh:codex-sign-out'),
  codexCancelLogin: () => ipcRenderer.invoke('dsh:codex-cancel-login'),
  onAntigravityEvent: callback => subscribe('dsh:antigravity-event', callback),
  onAntigravityGoal: callback => subscribe('dsh:antigravity-goal', callback),
  antigravityAccountState: () => ipcRenderer.invoke('dsh:antigravity-account-state'),
  antigravityAccountRefresh: () => ipcRenderer.invoke('dsh:antigravity-account-refresh'),
  antigravitySignIn: () => ipcRenderer.invoke('dsh:antigravity-sign-in'),
  onKimiEvent: callback => subscribe('dsh:kimi-event', callback),
  onKimiGoal: callback => subscribe('dsh:kimi-goal', callback),
});

// Ctrl + mouse wheel zoom (zoom by font/page size from any page).
window.addEventListener('wheel', (event) => {
  if (!event.ctrlKey && !event.metaKey) return;
  event.preventDefault();
  const direction = event.deltaY < 0 ? 1 : -1;
  void ipcRenderer.invoke('dsh:zoom-by-wheel', direction);
}, { passive: false });
