'use strict';

const { contextBridge, ipcRenderer, webUtils } = require('electron');

function subscribe(channel, callback) {
  const listener = (_event, data) => callback(data);
  ipcRenderer.on(channel, listener);
  return () => ipcRenderer.removeListener(channel, listener);
}

contextBridge.exposeInMainWorld('dshDesktop', {
  platform: process.platform,
  nativeSettingsView: true,
  settingsEmbedded: process.argv.includes('--workbench-settings'),
  showNativeSettings: (payload) => ipcRenderer.invoke('dsh:show-native-settings', payload),
  nativeSettingsReady: () => ipcRenderer.invoke('dsh:native-settings-ready'),
  onNativeSettingsReady: (callback) => subscribe('dsh:native-settings-ready', callback),
  getState: () => ipcRenderer.invoke('dsh:get-state'),
  openLogs: () => ipcRenderer.invoke('dsh:open-logs'),
  openSettingsWindow: (target) => ipcRenderer.invoke('dsh:open-settings-window', target),
  openMobileAccess: () => ipcRenderer.invoke('dsh:open-mobile-access'),
  openCliDevices: () => ipcRenderer.invoke('camellia:open-devices'),
  listCliServers: () => ipcRenderer.invoke('camellia:list-servers'),
  openCliServer: deviceId => ipcRenderer.invoke('camellia:open-server', { deviceId }),
  camelliaDevices: {
    call: (action, payload) => ipcRenderer.invoke('camellia:devices', { action, payload }),
    onEvent: callback => subscribe('camellia:device-event', callback),
    onTransfer: callback => subscribe('camellia:device-transfer', callback),
  },
  remoteControl: (action, payload) => ipcRenderer.invoke('dsh:remote-control', { action, payload }),
  engineSettingsGet: (payload) => ipcRenderer.invoke('dsh:engine-settings-get', payload),
  subscriptionPreferencesGet: payload => ipcRenderer.invoke('dsh:subscription-preferences-get', payload),
  subscriptionPreferencesSave: payload => ipcRenderer.invoke('dsh:subscription-preferences-save', payload),
  engineSettingsSave: (payload) => ipcRenderer.invoke('dsh:engine-settings-save', payload),
  runtimeState: () => ipcRenderer.invoke('dsh:runtime-state'),
  runtimeSetPath: (payload) => ipcRenderer.invoke('dsh:runtime-set-path', payload),
  runtimeSetPython: (payload) => ipcRenderer.invoke('dsh:runtime-set-python', payload),
  runtimePythonState: () => ipcRenderer.invoke('dsh:runtime-python-state'),
  appUpdateCheck: () => ipcRenderer.invoke('dsh:app-update-check'),
  appUpdateInstall: () => ipcRenderer.invoke('dsh:app-update-install'),
  runtimeEnsure: (payload) => ipcRenderer.invoke('dsh:runtime-ensure', payload),
  runtimeCheckUpdates: () => ipcRenderer.invoke('dsh:runtime-check-updates'),
  runtimeUpdate: (payload) => ipcRenderer.invoke('dsh:runtime-update', payload),
  runtimeReinstall: (payload) => ipcRenderer.invoke('dsh:runtime-reinstall', payload),
  runtimeReinstallPreview: (payload) => ipcRenderer.invoke('dsh:runtime-reinstall-preview', payload),
  downloadSettings: () => ipcRenderer.invoke('dsh:download-settings'),
  networkSettings: () => ipcRenderer.invoke('dsh:network-settings'),
  networkTest: () => ipcRenderer.invoke('dsh:network-test'),
  networkSaveSettings: payload => ipcRenderer.invoke('dsh:network-save-settings', payload),
  onNetworkHealth: callback => subscribe('dsh:network-health', callback),
  downloadSaveSettings: (payload) => ipcRenderer.invoke('dsh:download-save-settings', payload),
  onRuntimeState: (callback) => subscribe('dsh:runtime-state', callback),
  onRuntimePythonState: (callback) => subscribe('dsh:runtime-python-state', callback),
  onAppUpdateState: (callback) => subscribe('dsh:app-update-state', callback),
  benchmarkState: () => ipcRenderer.invoke('dsh:benchmark-state'),
  discussion: (action, payload = {}) => ipcRenderer.invoke('dsh:discussion', { action, payload }),
  onDiscussionEvent: callback => subscribe('dsh:discussion-event', callback),
  onDiscussionNavigate: callback => subscribe('dsh:discussion-navigate', callback),
  benchmarkStart: payload => ipcRenderer.invoke('dsh:benchmark-start', payload),
  benchmarkCancel: () => ipcRenderer.invoke('dsh:benchmark-cancel'),
  benchmarkReport: id => ipcRenderer.invoke('dsh:benchmark-report', { id }),
  benchmarkInstall: engine => ipcRenderer.invoke('dsh:benchmark-install', { engine }),
  benchmarkPrepareLibrary: library => ipcRenderer.invoke('dsh:benchmark-prepare-library', { library }),
  benchmarkExport: id => ipcRenderer.invoke('dsh:benchmark-export', { id }),
  benchmarkDelete: id => ipcRenderer.invoke('dsh:benchmark-delete', { id }),
  apiRouterExport: () => ipcRenderer.invoke('dsh:api-router-export'),
  apiRouterImport: () => ipcRenderer.invoke('dsh:api-router-import'),
  onBenchmarkState: callback => subscribe('dsh:benchmark-state', callback),
  onSettingsNavigate: (callback) => subscribe('dsh:settings-navigate', callback),
  onEngineSettingsChanged: (callback) => subscribe('dsh:engine-settings-changed', callback),
  onChatContentWidthChanged: (callback) => subscribe('dsh:chat-content-width-changed', callback),
  // Settings
  getSettings: () => ipcRenderer.invoke('dsh:get-settings'),
  saveSettings: (payload) => ipcRenderer.invoke('dsh:save-settings', payload),
  pickFile: (payload) => ipcRenderer.invoke('dsh:pick-file', payload),
  testRuntime: (payload) => ipcRenderer.invoke('dsh:test-runtime', payload),
  applySettings: () => ipcRenderer.invoke('dsh:apply-settings'),
  // Shared API pool (only masked credentials leave the main process).
  openApiSettingsWindow: () => ipcRenderer.invoke('dsh:open-api-settings-window'),
  apiRouterGetState: () => ipcRenderer.invoke('dsh:api-router-get-state'),
  subscriptionPricesRefresh: () => ipcRenderer.invoke('dsh:subscription-prices-refresh'),
  apiRouterSaveConfig: (payload) => ipcRenderer.invoke('dsh:api-router-save-config', payload),
  apiRouterRotate: (model) => ipcRenderer.invoke('dsh:api-router-rotate', model),
  apiRouterReset: (payload) => ipcRenderer.invoke('dsh:api-router-reset', payload),
  onApiRouterState: (callback) => subscribe('dsh:api-router-state', callback),
  ollamaProxyGetState: () => ipcRenderer.invoke('dsh:ollama-proxy-get-state'),
  providerInsights: () => ipcRenderer.invoke('dsh:provider-insights'),
  providerRefresh: (payload) => ipcRenderer.invoke('dsh:provider-refresh', payload),
  providerModels: (payload) => ipcRenderer.invoke('dsh:provider-models', payload),
  providerVerify: (payload) => ipcRenderer.invoke('dsh:provider-verify', payload),
  onProviderInsights: (callback) => subscribe('dsh:provider-insights', callback),
  workbenchSettings: () => ipcRenderer.invoke('dsh:workbench-settings'),
  onLanguageChanged: (callback) => subscribe('dsh:language-changed', callback),
  workbenchSaveSettings: (payload) => ipcRenderer.invoke('dsh:workbench-save-settings', payload),
  archivedSessionsList: () => ipcRenderer.invoke('dsh:archived-sessions-list'),
  archivedSessionAction: (payload) => ipcRenderer.invoke('dsh:archived-session-action', payload),
  onArchivedDeleteProgress: (callback) => subscribe('dsh:archived-delete-progress', callback),
  storageScan: () => ipcRenderer.invoke('dsh:storage-scan'),
  storageReferencesChanged: () => ipcRenderer.invoke('dsh:storage-references-changed'),
  storageClean: (token) => ipcRenderer.invoke('dsh:storage-clean', { token }),
  dataDirectoryMigrate: () => ipcRenderer.invoke('dsh:data-directory-migrate'),
  pluginCacheMaintain: () => ipcRenderer.invoke('dsh:plugin-cache-maintain'),
  dataExport: (scope) => ipcRenderer.invoke('dsh:data-export', { scope }),
  dataImport: (file, scope) => ipcRenderer.invoke('dsh:data-import', { file, scope }),
  onDataMigrationProgress: (callback) => subscribe('dsh:data-migration-progress', callback),
  onArchivedChanged: (callback) => subscribe('dsh:archived-changed', callback),
  codexDesktopSessions: () => ipcRenderer.invoke('dsh:codex-desktop-sessions'),
  codexDesktopImport: (ids) => ipcRenderer.invoke('dsh:codex-desktop-import', { ids }),
  codexDesktopSync: (id) => ipcRenderer.invoke('dsh:codex-desktop-sync', { id }),
  switchMode: (mode) => ipcRenderer.invoke('dsh:switch-mode', mode),
  onHarnessNavigate: callback => subscribe('dsh:harness-navigate', callback),
  conversationCommand: payload => ipcRenderer.invoke('dsh:conversation-command', payload),
  conversationSwitch: payload => ipcRenderer.invoke('dsh:conversation-switch', payload),
  conversationOpenHandoff: payload => ipcRenderer.invoke('dsh:conversation-open-handoff', payload),
  onConversationEvent: callback => subscribe('dsh:conversation-event', callback),
  onConversationGoal: callback => subscribe('dsh:conversation-goal', callback),
  onConversationStatus: callback => subscribe('dsh:conversation-status', callback),
  // Attachments: pick via native dialog / resolve dropped File objects
  pickAttachments: () => ipcRenderer.invoke('dsh:pick-attachments'),
  attachmentPath: (file) => webUtils.getPathForFile(file),
  saveClipboardImage: (payload) => ipcRenderer.invoke('dsh:save-clipboard-image', payload),
  savePastedText: (payload) => ipcRenderer.invoke('dsh:save-pasted-text', payload),
  previewFile: (filePath) => ipcRenderer.invoke('dsh:preview-file', filePath),
  resolveArtifacts: (payload) => ipcRenderer.invoke('dsh:resolve-artifacts', payload),
  openFileExternally: (filePath) => ipcRenderer.invoke('dsh:open-file-externally', filePath),
  revealFile: (filePath) => ipcRenderer.invoke('dsh:reveal-file', filePath),
  onCodexAccount: callback => subscribe('dsh:codex-account', callback),
  codexAccountState: payload => ipcRenderer.invoke('dsh:codex-account-state', payload),
  codexAccountRefresh: id => ipcRenderer.invoke('dsh:codex-account-refresh', { id }),
  codexAccountWake: id => ipcRenderer.invoke('dsh:codex-account-wake', { id }),
  codexSignIn: () => ipcRenderer.invoke('dsh:codex-sign-in'),
  codexAccountSelect: id => ipcRenderer.invoke('dsh:codex-account-select', { id }),
  codexAccountAdd: label => ipcRenderer.invoke('dsh:codex-account-add', { label }),
  codexAccountRemove: id => ipcRenderer.invoke('dsh:codex-account-remove', { id }),
  codexAccountLabel: (id, label) => ipcRenderer.invoke('dsh:codex-account-label', { id, label }),
  kimiAccountState: payload => ipcRenderer.invoke('dsh:kimi-account-state', payload),
  kimiAccountRefresh: id => ipcRenderer.invoke('dsh:kimi-account-refresh', { id }),
  kimiAccountWake: id => ipcRenderer.invoke('dsh:kimi-account-wake', { id }),
  kimiSignIn: () => ipcRenderer.invoke('dsh:kimi-sign-in'),
  kimiCancelLogin: () => ipcRenderer.invoke('dsh:kimi-cancel-login'),
  kimiOpenLogin: () => ipcRenderer.invoke('dsh:kimi-open-login'),
  kimiSignOut: () => ipcRenderer.invoke('dsh:kimi-sign-out'),
  kimiAccountSelect: id => ipcRenderer.invoke('dsh:kimi-account-select', { id }),
  kimiAccountAdd: label => ipcRenderer.invoke('dsh:kimi-account-add', { label }),
  kimiAccountRemove: id => ipcRenderer.invoke('dsh:kimi-account-remove', { id }),
  kimiAccountLabel: (id, label) => ipcRenderer.invoke('dsh:kimi-account-label', { id, label }),
  onKimiAccount: callback => subscribe('dsh:kimi-account', callback),
  codexSignOut: () => ipcRenderer.invoke('dsh:codex-sign-out'),
  codexCancelLogin: () => ipcRenderer.invoke('dsh:codex-cancel-login'),
  antigravityAccountState: () => ipcRenderer.invoke('dsh:antigravity-account-state'),
  antigravityAccountRefresh: () => ipcRenderer.invoke('dsh:antigravity-account-refresh'),
  antigravityAccountRefreshUsage: () => ipcRenderer.invoke('dsh:antigravity-account-refresh-usage'),
  antigravityAccountLabel: label => ipcRenderer.invoke('dsh:antigravity-account-label', { label }),
  onAntigravityAccount: callback => subscribe('dsh:antigravity-account', callback),
  antigravitySignIn: () => ipcRenderer.invoke('dsh:antigravity-sign-in'),
});

// Ctrl + mouse wheel zoom (zoom by font/page size from any page).
window.addEventListener('wheel', (event) => {
  if (!event.ctrlKey && !event.metaKey) return;
  event.preventDefault();
  const direction = event.deltaY < 0 ? 1 : -1;
  void ipcRenderer.invoke('dsh:zoom-by-wheel', direction);
}, { passive: false });
